spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/recipe
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
server:
  servlet:
    context-path: /recipe
